백준_2주차문제풀이
IDU-IFP/ifp-2022-restart-ok pull request #16
Opened 2022-05-03 12:32 UTC by peridot-28

소이연 2주차 문제풀이 제출합니다.

- [기술 블로그 링크](https://peridot-28.tistory.com/)
- solved.ac의 한 주간 학습 성장 사진
![백준히스토리1](https://user-images.githubusercontent.com/100713189/166453264-702f760c-b85a-4c4d-a366-61dc32aca55d.png)

2022-05-07 11:14 UTC, overtae reviewed
코드 설명을 주석으로 추가한 게 너무 좋았습니다! 이번 주차도 수고하셨어요!

2022-05-07 11:14 UTC, overtae commented on soyiyeon/백준_9325번문제.py
> +    price = s
```suggestion
    price = int(input())
    n = int(input())
```
따로 s가 사용되지 않는다면 처음부터 price로 받아도 될 것 같습니다.

2022-05-07 11:14 UTC, overtae commented on soyiyeon/백준_10833번문제.py
> +for _ in range(N):
```suggestion
# N = int(input())
answer = 0
for _ in range(int(input()):
```
N이 따로 사용되지 않는다면 for 문에서 바로 입력받는 방법도 있겠네요!

2022-05-14 13:52 UTC, blooper20 commented
늦게 확인해서 죄송합니다...
solved.ac의 한 주간 학습 성장 사진 맞게 올려주셔서 감사합니다!!

2022-05-16 02:51 UTC, overtae reviewed
이번 주도 수고하셨습니다 ㅎㅎ

2022-05-16 02:51 UTC, overtae commented on soyiyeon/백준_10178번문제.py
> +    print(f'You get {c//v} piece(s) and your dad gets {c%v} piece(s).')
문자열 포맷 사용하니까 깔끔하고 보기 좋네요!

2022-05-16 02:51 UTC, overtae commented on soyiyeon/백준_10952번문제.py
> +    if a == 0 and b == 0:
```suggestion
    if not a and not b:
```
이런 방법도 있겠네요!

2022-05-16 02:51 UTC, overtae commented on soyiyeon/백준_2446번문제.py
> +    print(" "*(N-i) + "*"*(2*i-1))
```suggestion
    print(" "*(N-i) + "*"*(2*i - 1))
```
파이선 코딩 컨벤션 (https://peps.python.org/pep-0008/#other-recommendations) 참고해서 작성하면 더 좋을 것 같습니다!

2022-05-16 02:51 UTC, overtae commented on soyiyeon/백준_2523번문제.py
> +    print("*"*(j))
```suggestion
    print("*" * j)
```
괄호를 사용하지 않아도 좋을 것 같습니다!

2022-05-23 09:40 UTC, tjqehd23 commented on soyiyeon/백준_2445번문제.py
> +    print("*"*(i) + " "*(2*(N-i)) + "*"*(i))
for j in range(N,0,-1):
    print('*'*j+' '*((N-j)*2)+'*'*j)

2022-05-23 09:41 UTC, tjqehd23 commented on soyiyeon/백준_2445번문제.py
> +    print("*"*(i) + " "*(2*(N-i)) + "*"*(i))
> for j in range(N,0,-1):
    print('*'*j+' '*((N-j)*2)+'*'*j)

2022-05-23 10:09 UTC, tjqehd23 reviewed
잘 보고 갑니다 :)

2022-05-23 10:09 UTC, D-Sup commented on soyiyeon/백준_2445번문제.py
> +    print("*"*(i) + " "*(2*(N-i)) + "*"*(i))
```suggestion
	for i in range(N,0,-1):
    print('*'*i+' '*((N-i)*2)+'*'*i)
```
이렇게 줄여서 쓸 수도 있겠네요!

2022-05-23 10:09 UTC, tjqehd23 commented on soyiyeon/백준_9295번문제.py
> +    print(f'Case {x+1}: {y+z}')
f-string 문법을 사용해서 표현하니까 깔끔하네요~

2022-05-23 10:11 UTC, tjqehd23 requested changes
잘보고 갑니다~!

2022-05-23 10:12 UTC, tjqehd23 commented
>

2022-05-23 10:32 UTC, tjqehd23 commented
> 잘보고 갑니다~!!

2022-05-24 07:25 UTC, merged